name: 'decK action'
description: 'Declarative Configuration management for Kong'
branding:
  icon: 'repeat'  
  color: 'green'
inputs:
  command:
    description: 'decK command you want to execute'
    required: true
    default: 'ping'
  kong_workspaces:
    description: 'Kong workspaces where yaml should be located'
    required: true
    default: 'kong'
  github_token:
    description: 'GitHub Token'
    required: true
  options:
    description: 'option arguments'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.kong_workspaces }}
    - ${{ inputs.options }}
    - ${{ inputs.github_token }}
