name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  kong-addr:  # id of input
    description: 'Kong Address'
    required: true
    default: 'http://localhost:8001'
  headers:  # id of input
    description: 'Kong Headers'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs['kong-addr'] }}
    - ${{ inputs.headers }}